### DISCUSSION TITLE
Need help with configuring GraphQL VSCode extension for monorepo

### DISCUSSION THREAD

**Discussion by Poolshark** [graphql/graphiql#2367] [Q&A / Support] [answered]
Hi!

I'm a bit stuck and also a bit confused with how to set up the extension properly. So if anyone could help this would be highly appreciated!

#### Setup
I have a monorepo with roughly the following structure
```
frontend/
  apps/
    app1/
    app2/
  packages/
    components/
    providers/
    ...
schema/
  admin/
    schema.graphql
    schema.ts
  client/
    schema.graphql <<< remote fetched - contains definitions from graphql/source AND some directives which are generated by the server
    schema.ts
  extensions/
    app1.graphql
  graphQl/
    source/
      ... *.graphql files
    schema.graphql <<< generated GraphQL file from *graphql files in source
scripts/
  ... *.ts some script files which eg. deploy the schema to the server
```

- So basically I have some `react` applications in my `frontend/` folder which **all** rely on `schema/client/schema.grapqh`. Each app however, can have it's own **schema extension**, eg. for `app1` this would be `schema/extensions/app1.graphql`. 

- There is a also **scripts** inside the `scripts` folder which rely on `schema/admin/schema.graphql` - these are all `*.ts` files.

- Finally, there is the **schema definition** for the client schema, which is found in `schema/graphQl/source` - this is all `*.graphql` files.

This is my `.graphqlrc`
```
projects:
  default:
    schema:
      - ./schema/client/schema.graphql
    extensions:
      app1:
        - ./schema/extensions/app1.graphql
  scripts:
    schema:
      - ./schema/admin/schema.graphql
    documents:
      - ./scripts/*.ts
  source:
    documents:
      - ./schema/graphQl/source/**/*.graphql
```

#### The Problem(s)
I've got mot of it more or less working but I'm struggling with the following things. First off all, I do not understand how **projects** are supposed to work. How does the extension know which "project" is meant? For example, how does the extension know that with
```
projects:
  app1:
    schema:
      ...
```
I mean the project `app1`? Does it parse the `package.json` files and check the projects?

##### 1. Schema extensions
I've tried to add the file `schema/extensions/app1.graphql` to the default "project" with
- `documents` which causes the extension to crash because it does not understand how a schema extension works (I get the error that some fields which I extend via the schema extension aren't defined in the schema file).
- `extensions` (see above). This gets simply ignored, since I don't get type definitions in `app1` for the schema extension

##### 2. The scripts folder
I always get the error
```
Unable to find any GraphQL type definitions for the following pointers:
        
          - ./scripts/*.ts
```
The funny thing here is, that I still get all type definitions for eg. mutations in my script files. So I assume that somehow the `schema/admin/schema.graphl` gets found and applies to my scripts...

##### 3. The schema definition
This is the bit which might be not working at all but I could live with the status quo. As mentioned, all my types and interfaces which define my **client schema** are in `schema/graphQl/source/**/*.graphql`. I generate a local schema file in `schema/graphQl/schema.graphql` from all this files which then gets deployed to the server. The server generates the **client schema** which is stored in `schema/client/schem.graphql`. In order to get type hints and errors for all the directives, I need the remote schema for all my type definitions. Obviously the extension crashes if I use the **client schema** and all my types in the same project, since they would be redefined.

Currently, it works with the downside that _click to definition_ leads me to the definition in the schema file rather that to the definition within my `source` folder.

I know this is quite a lengthy question but I really hope someone could get me at least some hints to push me in the right direction! I'm struggling with this since nearly a month!

Thanks! 🙌

**Comment by Poolshark** [comment, marked as answer]
If someone is also struggling with this - I think a had a profound misunderstanding of how GraphQL config works!

The following `.graphqlrc` solved the problem for me (the _goToDefinition_ in my GraphQL files still redirects me to the client schema file but this is something I can live with)
```yml
projects:
  default:
    schema:
      - ./schema/client/schema.graphql
      - ./schema/extensions/*.graphql
      - ./schema/relay/relayDirectives.graphql
    documents:
      - ./frontend/**/*.{ts,tsx}
  scripts:
    schema:
      - ./schema/admin/schema.graphql
  source:
    schema:
      - ./schema/graphQl/source/**/*.graphql
```
I still don't understand **projects**, so if someone can help - very much appreciated.
