### DISCUSSION TITLE
[vscode extension] Duplicate fragment names in different projects

### DISCUSSION THREAD

**Discussion by benatshippabo** [graphql/graphiql#2402] [General] [answered]
Hi, so we have several projects defined in our `.graphqlrc.yml` file:

```yml
projects:
  server:
    schema: 'server/packages/server/schema.graphql'
    documents: 'server/packages/**/*.{js,ts}'
  frontend:
    schema: 'server/packages/server/schema.graphql'
    documents: 'frontend/packages/*/src/**/*.{js,ts,tsx,graphql}'
```

This is our simplified monorepo file structure:

```
.
├── frontend
└── server
```

We have fragments with the same name in both projects:

```gql
# frontend
fragment UserContactFields on User {
  _id
  name
  email
  phone
  address
}

# server
fragment UserContactFields on User {
  _id
  name
  email
}
```

But going to the definition of a usage in the `frontend` project takes us to the definition in the `server`, or vice versa depending on which file is opened first.

My question is if the fragments are in different projects, why does going to the definition of a fragment in one project take us to a different project's fragment? Is this expected behavior?
