### ISSUE TITLE
Hover over named types doesn't work anymore

### ISSUE THREAD

**Issue by divyenduz** [graphql/graphiql#1307]
Funnily enough, this has a [test case](https://github.com/graphql/graphiql/blob/36ed6695ce2b3f2608a0a679d12df64ed7a9b2bb/packages/graphql-language-service-interface/src/__tests__/GraphQLLanguageService-test.ts#L103-L112) that I [wrote for fun](https://github.com/graphql/graphql-language-service/pull/243/files) originally and the test passes.

**Comment by divyenduz** [comment]
Edited the title, actually, hover doesn't work for named types and built in types. Since, the tests are passing, it must be broken at some other level. I don't see the logs for hover RPC when connected to the extension (might be related https://github.com/graphql/graphiql/issues/1306)

**Comment by divyenduz** [comment]
Did some digging, it is failing (returning nothing), because in this file `packages/graphql-language-service-interface/src/GraphQLLanguageService.ts`, this function `getHoverInformation`, this block produces a `null` schema. 

```
const schema = await this._graphQLCache
      .getSchema(projectConfig.projectName)
      .catch(() => null);
```

The project name is correctly fulfilled. For reference, my `.graphqlconfig` looks like this: 

```
projects:
  app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000/graphql
        alternate: http://localhost:4000/graphql
```

**Comment by divyenduz** [comment]
I am pretty sure that I am using an older format of GraphQL config. Looking for some docs that tell me about the breaking changes 😅

**Comment by divyenduz** [comment]
Did some more digging and this fails at `defaultRawEndpoint = endpointsExtension.getRawEndpoint();` in `GraphQLCache.ts` file. 

If I wrap that code in try-catch, I get the following error: 

`Error: You have to specify endpoint name or define GRAPHQL_CONFIG_ENDPOINT_NAME environment variable`

I lack the context of the new GraphQL config and its extension API. @acao maybe you know more?

**Comment by divyenduz** [comment]
Update, removing the alternate endpoint from config makes it go further (not the same error as last comment), but still no success, digging further (maybe tomorrow, sleep time)

```
projects:
  app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000/graphql
```
