### ISSUE TITLE
feat: go-to-definition for source files rather than from generated config schema result

### ISSUE THREAD

**Issue by ilyavolodin** [graphql/graphiql#1672]
## Actual Behavior

When using "Go to definition" in one of the .graphql files, it always opens auto-generated generated-schema.graphql file, instead of the source code.

## Expected Behavior

Correctly navigate to the source file.

## Steps to Reproduce the Problem Or Description

.graphqlrc.yml file:
```
overwrite: true
schema:
  - "./src/typeDefs/*.graphql"
generates:
  ./src/schema.generated.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      noSchemaStitching: true
      optionalInfoArgument: true
      contextType: ./context#Context
  ./types/generated.ts:
    plugins:
      - "typescript"
    config:
      noSchemaStitching: true
```

This is in apollo server project. All schema files are located in the same folder: `./src/typeDefs/*.graphql`. I have a number of .graphql files that have type definitions for the server. This is happening to all types, as far as I can tell.

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.1
  - VSCode Version: 1.47.3
  - OS Name: OSX Mojave
  - OS Version: 10.14.6

## Logs Of TS Server || GraphQL Language Service

<details>
  <summary>Logs</summary>

  ```text
8/31/2020, 12:43:37 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}

undefined
8/31/2020, 12:43:37 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
[Error - 12:43:42 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Definition not found for GraphQL type CommentEdge
  Code: -32603 
8/31/2020, 12:43:43 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/definition","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
8/31/2020, 12:43:43 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didClose","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:43 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:45 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/definition","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
8/31/2020, 12:43:45 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didClose","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:46 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
8/31/2020, 12:43:46 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/definition","projectName":"default","fileName":"file:///Users/ivolodin/Code/orchestration/src/typeDefs/comments.graphql"}

undefined
8/31/2020, 12:43:46 PM [4] (pid: 90841) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///var/folders/lq/qs7z73kn4fb7b2csz2j323943khnrg/T/graphql-language-service/orchestration/projects/default/generated-schema.graphql"}

undefined
  ```
</details>

**Comment by acao** [comment]
this is the code in question:

https://github.com/graphql/graphiql/blob/f0226dd05084a65a4286dd957717e446a01ce3bc/packages/graphql-language-service-server/src/MessageProcessor.ts#L886

hilariously, i accidentally left a useful console.log statement on the last publish. so if you have v 0.3.8, and you open the appropriate output channel, what do you see this value as?

**Comment by acao** [comment]
good news! i tracked it down. issuing a new patch release here in a few minutes...

**Comment by acao** [comment]
ok! @zatloeri @ilyavolodin  - `0.3.9` should fix your issue.
there was a pluralization typo in the manifest :((

the README herein has been updated with the proper spelling of this config path - `useSchemaFileDefinitions`

**Comment by zatloeri** [comment]
Thank you for the quick reply and fix.
I have tested on the newest version of the extension (`graphql.vscode-graphql 0.3.9`) and it seems to work if I alter my `config` to:
```
schema: "./src/api/**/*.gql"
documents: "./src/api/**/*.gql"
extensions:
  vscode: 
    cacheSchemaFiles: true
    cacheConfigSchema: false
```

**Now the `go-to definition` action work as expected**
**But autocomplete is still not working**

I added documents since the `readme` states 
> To support language features like "go-to definition" across multiple files, please include documents key in the graphql-config default or /per project (this was include in 2.0).

I see error messages about duplicate types and no found definitions after I added the `documents` part.
The errors are for example:

```
Unable to find any GraphQL type definitions for the following pointers:
        
          - ./src/api/**/*.gql

```
And
```
(node:42181) UnhandledPromiseRejectionWarning: Error: Type "Message" already exists in the schema. It cannot also be defined in this type definition.
```

When I remove the `documents` part, then the errors are gone, but `go-to definition` stops working.
It will not go anywhere and acts as the definition does not exist.
Setup of my files is the same as I showed in my last comment.
I think I am doing something horribly wrong.
Is there still a problem with my `config` or is it my file setup?

**Comment by acao** [comment]
@zatloeri to be clear, `documents` is only required for files which don't contain schema. for example, files containing operations or fragments.  `schema` includes everything. so you don't want to have overlapping `schema` and `document` pointers. I will need to update the readme to make all of this more clear.

also, now this:
```yml
extensions:
  vscode: 
    cacheSchemaFiles: true
    cacheConfigSchema: false
```

has become this in the stable release:

```yml
extensions:
  languageService:
    useSchemaFileDefinitions: true
```

**Comment by zatloeri** [comment]
@acao Thanks for replying so quick.

I feel like it will be some stupid mistake (I am misunderstanding something) cause I have created a simple example [repo](https://github.com/zatloeri/GraphQLExtTest)  and even there, it is not working for me.
It acts like the definitions do not exist with no error.

**Comment by jesselee34** [comment]
Something I just noticed after having the same issue myself, the go-to-definition works as expected when `schema` and `documents` are both defined with the same glob pattern, but stops working if I remove `documents`

After reading through this thread I wanted to try this (I realize `documents` shouldn't be defined like this) 
```
schema: "./server/schema/**/*.gql"
documents: "./server/schema/**/*.gql"
extensions:
  languageService:
    useSchemaFileDefinitions: true
```
For some reason the go-to definition works like expected with the above, but...

```
schema: "./server/schema/**/*.gql"
extensions:
  languageService:
    useSchemaFileDefinitions: true
```

...does not work. F12 gives me "No definition found for TestType"

Now that I've tracked this thread down and I have some idea where the bug might reside I'm going to spend some time looking into it myself. If I find it I'll see about making a pull request.
