### ISSUE TITLE
Search icon misalignment issue

### ISSUE THREAD

**Issue by benjie** [graphql/graphiql#1773]
To reproduce, visit https://graphql.org/swapi-graphql/, open the docs, and look at the `Search Schema` input; you'll see the search icon is out of place:

![Screenshot_20210122_174716](https://user-images.githubusercontent.com/129910/105526573-86da2000-5cda-11eb-8d51-f0939b65b40e.png)

I've worked around this in PostGraphile with this CSS snippet:

```css
.graphiql-container .search-box-icon {
  line-height: 1em;
  top: 1px;
}
```

but I'm not sure if this is the intended styling (in particular the `top: 1px` feels wrong), hence I've not opened a PR.
