### ISSUE TITLE
graphiql css conflicts with existing codemirror css

### ISSUE THREAD

**Issue by ashharrison90** [graphql/graphiql#1822]
Hi! I'm seeing an issue in our project where using this package conflicts with our existing use of `codemirror`.

I think you have a copy of the CodeMirror css here: https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/css/codemirror.css#L141

However around a year ago there was a commit in the main CodeMirror repo to increase these margins from 30px to 50px: https://github.com/codemirror/CodeMirror/commit/632f30be88392aa8e86a5e28697df78f759cc913

```css
// From graphiql
.CodeMirror-scroll {
    height: 100%;
    margin-bottom: -30px;
    margin-right: -30px;
    outline: none;
    overflow: scroll !important;
    padding-bottom: 30px;
    position: relative;
}

// From CodeMirror
.CodeMirror-scroll {
    overflow: scroll !important;
    margin-bottom: -50px;
    margin-right: -50px;
    padding-bottom: 50px;
    height: 100%;
    outline: none;
    position: relative;
}
```

The result of this is if you pull in CodeMirror's css and graphiql's css, you can end up with ugly scrollbars in places they shouldn't be. 😭 

I don't know enough about the use of CodeMirror in this project to fully fix this, but my speculative suggestion would be to wrap the copy of the CodeMirror css in a containing class so it's only scoped to this repo's use and doesn't conflict globally. 

Hope that all makes sense. Appreciate your thoughts!
