### ISSUE TITLE
Autocomplete doesn't work with remote schema

### ISSUE THREAD

**Issue by madeleineostoja** [graphql/graphiql#2018]
## Actual Behavior

When using a remote schema (with a custom fetch in my case) autocomplete fails silently. When I generate a schema from introspection from that same schema definition with `graphql-cli` and use that, autocomplete works again.

My config (for [Prismic](https://prismic.io)

```yaml
schema:
  https://heybokeh.cdn.prismic.io/graphql:
    customFetch: 'codegen-prismic-fetch'
documents: './src/**/*.{graphql,ts,tsx}'
...
```

## Expected Behavior

This extension should work with remote schemas defined in graphql config

## Steps to Reproduce the Problem Or Description

1. Specify remote schema with custom fetch in graphql config
2. Try write queries, see that autcomplete doesn't work

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.18
  - VSCode Version: 1.60.2
  - OS Name: macOS
  - OS Version: 11.4
