### ISSUE TITLE
Support for schema typedefs in TS

### ISSUE THREAD

**Issue by brpatel0202** [graphql/graphiql#2338]
## Actual Behavior

I am using [https://www.graphql-tools.com/docs/merge-typedefs](https://www.graphql-tools.com/docs/merge-typedefs) with graphql-tag to maintain separate typedefs in Typescript.
So all my schema files are in ts files.

Below is my .graphqlrc.yml file

```
schema: "src/**/*.{graphql,tsx,jsx,ts,js}"
documents: "src/**/*.{graphql,tsx,jsx,ts,js}"
extensions:
  languageService:
    useSchemaFileDefinitions: true

```

After setting above configurations, I am not able to use vscode-graphql extension features with multiple ts schema files.
Can you please provide example on how to use vscode-graphql extension with ts files. Also is it mandatory to use gql tag for this extension or it can be work with `#graphql .. `

## Expected Behavior

As per documentation feature guideline ```Load the extension on detecting gql tag in js, ts, jsx, tsx, vue files```,  loading in ts files should be accessible through this extension and provide intelligence and error handling for schema typedefs.

## Specifications

  - GraphQL for VSCode Extension Version:  vscode-graphql
  - VSCode Version: 1.49.3
  - OS Name: Windows

**Comment by Yimiprod** [comment]
Hi, any update on this issue please ?

I have something like this:
```yml
# @type {import('graphql-config').IGraphQLConfig}
schema:
  - './packages/graphql/src/schemas/schemas.ts'
documents:
  - './packages/front/lib/graphql/documents/**/*.(gql|graphql)'
```

Where schema.ts extract all in one big string using `printSchemaWithDirectives` from `@graphql-tools/utils`
