### ISSUE TITLE
LSP Server: No Errors on mismatched file

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2498]
> there was an error loading the project config for this file e: File <file> doesn't match any project

This error should be trapped and hidden on save/change. It is irrelevant.

**Comment by vitexikora** [comment]
Yes, it should. 
What is the status of this @acao please?

Currently I get logged this:
```
there was an error loading the project config for this file xTt: File '...\DiningOffer.tsx' doesn't match any project
```

My graphql-config is configured to ignore all ts(x) files, since my only GQL is in GQL files.
```yaml
schema: 'src/core/graphql/schema/generated.graphql.schema.json'
documents:
  - src/modules/**/*.gql
exclude:
  - "**/*.{ts,tsx}"
```
