### ISSUE TITLE
"`this.splice()` is not a function" error on `vscode-graphql` startup

### ISSUE THREAD

**Issue by VictorGaiva** [graphql/graphiql#2619]
My VSCode plugin is failing to start, logging the following error:

![image](https://user-images.githubusercontent.com/13839490/182178999-081eb51a-7855-4467-9356-0bdd590b8a58.png)
```
8/1/2022, 11:58:03 AM [1] (pid: 32510) graphql-language-service-usage-logs: WARNING: graphql-config error, only highlighting is enabled:
this.splice is not a function
```
and
```
[Error - 12:05:13 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: this.splice is not a function
  Code: -32603 
```

This is my current `.graphqlrc.yml`
```yml
schema: "http://localhost:4000/_introspect"

maybeValue: T
config:
  enumsAsTypes: true
  useTypeImports: true
  nonOptionalTypename: true
  scalars:
    Time: number
    DateTime: Date
    Json: Record<string, unknown>
generates:
  app/types/apollo.gql.d.ts:
    plugins:
      - typescript-apollo-client-helpers
  app/types/schema.gql.d.ts:
    documents: "**/*.gql"
    plugins:
      - typescript
  app/:
    documents: "**/*.gql"
    preset: near-operation-file
    presetConfig:
      baseTypesPath: "types/schema.gql.d.ts"
      extension: .gql.d.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
```

The same setup was working up to last Friday, and is still working on my colleagues machines.
