### ISSUE TITLE
No language features for .graphql files since v0.5.0 (only colorization)

### ISSUE THREAD

**Issue by MariaSolOs** [graphql/graphiql#2671]
I've been trying to make the latest versions of this extension to work but it seems like completion (and most other language features) broke since `v0.5.0`. Note that everything works fine in `v0.4.15`.

The project I'm currently working on is [here](https://github.com/MariaSolOs/paradigm), in case you want to check out my setup. But as a summary, my `graphql.config.json` file looks like this:
```
{
    "schema": "./graphql-server/introspection.json",
    "documents": "./graphql-server/**/*.graphql"
}
```
And I'm using [codegen](https://www.graphql-code-generator.com/) with the following configuration:
```
schema: './graphql-server/schema.ts'
documents: './graphql-server/**/*.graphql'
generates:
  ./graphql-server/introspection.json:
    plugins:
      - introspection
    config:
      minify: true
  ./graphql-server/sdk.ts:
    plugins:
      - add:
          content: '// @ts-nocheck Ignore this file, it is just codegen output'
      - typescript
      - typescript-operations
      - typescript-graphql-request
      - plugin-typescript-swr
    config:
      skipTypename: true
  ./graphql-server/resolvers-types.ts:
    plugins:
      - add:
          content: '// @ts-nocheck Ignore this file, it is just codegen output'
      - typescript
      - typescript-resolvers
```

The logs only show the following:
```
8/14/2022, 2:55:11 PM [3] (pid: 7005) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
```
