### ISSUE TITLE
[lsp-server] only one of multiple projects in graphqlrc work in vscode

### ISSUE THREAD

**Issue by scamden** [graphql/graphiql#3153]
## Current Behavior
I have two projects configured in my rc as indicated on the vscode extension readme. Whichever project I load a file from first gets cached and works (ish there are issues with line numbers and the `gql` tag but that's for another issue). But the files from the other project will not function. 

Based on my loose naive reading of the code it seems like `getFragmentDefinitions` inside `GraphQLCache.ts` caches according to `projectConfig.dirpath` which would have to be the same for both projects. I forked and tried adding the project name to the cache key and it seemed to solve but I have no idea if that could cause other issues.

Here's my config
```yaml
projects:
  app-dashboard:
    schema:
      - ./workspaces/server/graphql/shared/shared-schema.graphql
      - ./workspaces/server/graphql/dashboard/dashboard-schema.graphql
    documents:
      - ./workspaces/app-dashboard/cache.tsx
      - ./workspaces/app-dashboard/pages/_app.tsx
      - ./workspaces/app-dashboard/{components,pages,utils}/**/*.{ts,tsx}
      - ./workspaces/shared-frontend/{components,hooks,utils}/**/*.{ts,tsx}
    extensions:
      languageService:
        enableValidation: false
  app-admin:
    schema:
      - ./workspaces/server/graphql/shared/shared-schema.graphql
      - ./workspaces/server/graphql/admin/admin-schema.graphql
    documents:
      - ./workspaces/app-admin/cache.tsx
      - ./workspaces/app-admin/pages/_app.tsx
      - ./workspaces/app-admin/{components,pages,utils}/**/*.{ts,tsx}
      - ./workspaces/shared-frontend/{components,hooks,utils}/**/*.{ts,tsx}
    extensions:
      languageService:
        enableValidation: false

```

## Desired Behavior
Two projects in the same config both have go to definition working. 

## PRs welcome!

If you find a way to solve this problem by modifying the code in either the source or the distributed code, we are more than happy to accept enhancement requests as PRs!
