### ISSUE TITLE
[graphiql] @graphiql/toolkit tried to access graphql-ws (a peer dependency) but it isn't provided by its ancestors

### ISSUE THREAD

**Issue by simPod** [graphql/graphiql#3299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is the same issue as https://github.com/graphql/graphiql/issues/2428. 

First happened in v1. Then disappeared in v2. Now reappeared again in v3.

### Module pattern

- [ ] graphiql-umd
- [ ] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version:
- OS:
- Browser:
- Bundler:
- `react` Version:
- `graphql` Version:
```

**Comment by simPod** [comment]
This time, the fix is

```yaml
packageExtensions:
  "@graphiql/toolkit@*":
    dependencies:
      graphql-ws: "*"
```
