### ISSUE TITLE
[lsp-server] 🐞 The language server throws "could not parse the TypeScript file" error for every TS file when `documents` field is used

### ISSUE THREAD

**Issue by HosseinAgha** [graphql/graphiql#3415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The language server throws `Could not parse the TypeScript file. SyntaxError: Unexpected token, expected ","` errors when I use `documents` section in GraphQL config.  
The Config:  
```yaml
projects:
  apps:
    schema: https://localhost:8080/graphql
    documents:
      - ./app/**/*.{ts,tsx}
      - '!(app/operations/generated/*)'
      - '!(app/operations/gqlApolloHooks.ts)'
```

The Other Config That I tested: 
```yaml
projects:
  apps:
    schema: https://localhost:8080/graphql
    documents:
      - ./app/**/*.{ts,tsx}
      - '!./app/operations/generated/*.{ts,tsx}'
      - '!./app/operations/gqlApolloHooks.ts'
``` 

And here is a trick config that works:
```yaml
projects:
  apps:
    schema: https://localhost:8080/graphql
    include:
      - ./app/**/*.{ts,tsx}
    exclude:
      - './app/operations/generated/*.{ts,tsx}'
      - './app/operations/gqlApolloHooks.ts'
``` 

### Expected Behavior

It should not throw TypeScript errors and just work.

### Environment

* LSP Server Version: VSCode GraphQL v0.8.17
* OS: macos
