### ISSUE TITLE
[graphiql] VSCode multi project support

### ISSUE THREAD

**Issue by usama8800** [graphql/graphiql#3418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Autocomplete shows only `q1` as a query and gives an error on `q2`

### Expected Behavior

The readme says it supports multiple projects so autocomplete should show `q1` and `q2`

### Steps To Reproduce

Files
```yml
# graphql.config.yml
projects:
  p1:
    schema: s1.graphql
  p2:
    schema: s2.graphql
```
```graphql
# s1.graphql
type Query {
  q1: Int
}
```
```graphql
# s2.graphql
type Query {
  q2: Int
}
```

### Environment

* GraphiQL Version: v0.3.18
* VSCode Version: 1.81.1
* OS: Windows
