### ISSUE TITLE
[vs-code-graphq] Add option to define the path to download the schema

### ISSUE THREAD

**Issue by feinstein** [graphql/graphiql#3887]
I am moving from IntelliJ to VS Code and in IntelliJ the official GraphQL extension allows me to download the schema into a file, it shows this button, which downloads the schema to the file that I defined:

![Image](https://github.com/user-attachments/assets/bb09d659-d04a-4d25-bafb-0ef4494b9c2f)

This is my config file:

```yaml
schema: ./lib/app/data/data_sources/schema.graphql
documents: '*/.graphql'
extensions:
  endpoints:
    Dev:
      url: https://mysite.com/server-graphql
```

As you can see I defined the URL where the schema can be fetched from and the file path where it should be downloaded.

This feature is really important to me because I run a code gen tool that will transform the queries and graphql data types into Dart code, and it can only run from a local file.
