### ISSUE TITLE
Embedding GraphiQL + html overflow: hidden

### ISSUE THREAD

**Issue by D1plo1d** [graphql/graphiql#71]
I'm trying to embed GraphiQL in a site however the overflow: hidden at the top off app.css prevents the rest of my site from working (as a single page app everything shares a single css file):
```css
html, body {
  height: 100%;
  margin: 0;
  overflow: hidden;
  width: 100%;
}
```

Would it be possible to extract the shared css into a file and move the html + body height fixes to a separate file for standalone GraphiQL setups?
