### ISSUE TITLE
Proposal: improve visibility of <code> tag in doc explorer

### ISSUE THREAD

**Issue by yroseau** [graphql/graphiql#949]
When we add code with backquote in graphql documentation, it's not easy to read.

Now:
![Screenshot from 2019-08-27 15-28-09](https://user-images.githubusercontent.com/9842982/63775364-79e7b000-c8df-11e9-95c5-aeb8101581d3.png)

Proposal:
![Screenshot from 2019-08-27 15-25-01](https://user-images.githubusercontent.com/9842982/63775369-7d7b3700-c8df-11e9-8ce5-bbcce8264098.png)

```css
code, pre {
    --saf-0: rgba(var(--sk_foreground_low,29,28,29),0.13);
    font-size: 12px;
    line-height: 1.50001;
    font-variant-ligatures: none;
    white-space: pre;
    white-space: pre-wrap;
    word-wrap: break-word;
    word-break: normal;
    -webkit-tab-size: 4;
    -moz-tab-size: 4;
    tab-size: 4;
}
code {
    padding: 2px 3px 1px;
    border: 1px solid var(--saf-0);
    border-radius: 3px;
    background-color: rgba(var(--sk_foreground_min,29,28,29),.04);
    color: #e01e5a;
    background-color: white;
}
```
